spring.application.name: rest
springdoc.swagger-ui.path: /swagger-ui.html
management.endpoints.web.exposure.include: '*'
spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    streams:
      application-id: my-kafka-streams-app
      bootstrap-servers: localhost:9092
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    auto-create-topic-name: vein-chain-topic
    admin:
      properties:
        bootstrap.servers: localhost:9092